remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Basic Information 
title: Felipe Cisternas Álvarez
position: M.Sc in Computer Science
description: Computer Science Engineer
affiliation: null
email: fcisternas.dev@gmail.com
name: ""

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar:
cv_link: projects/Felipe_Resume.pdf
github_link: https://github.com/ftcister
linkedin: https://linkedin.com/in/felipecisternasalvarez
twitter: https://twitter.com/ftcister

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: AI Machine Learning Deep Learning Data Science Engineer
#description: Portfolio of Felipe Cisternas Computer Science Engineer and Msc in Computer Science
canonical: https://ftcister.github.io/portfolio/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
logo: assets/img/avatar.png
avatar: assets/img/avatar.png
favicon: assets/img/favicon.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: false

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: 

