remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

name: ""
logo: /assets/img/logo.png
title: Felipe Cisternas Álvarez
description: Computer Science Engineer
email: fcisternas.dev@gmail.com

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/
cv_link: projects/Felipe_Resume.pdf
github_link: https://github.com/ftcister
linkedin: https://linkedin.com/in/felipecisternasalvarez

